postgresql: error when using sequence on v10+
Sequence handling has been changed on postgresql 10

When runing benerator generate command and using
DBSequenceGenerator we get the following error:

```
java.lang.RuntimeException: Error executing query: select sequence_name,
        start_value, increment_by, max_value, min_value, is_cycled,
        cache_value, last_value from accounts_id_seq
    at com.rapiddweller.jdbacl.DBUtil.executeQuery (DBUtil.java:1014)
    at com.rapiddweller.jdbacl.DBUtil.querySingleRow (DBUtil.java:946)
    at com.rapiddweller.jdbacl.dialect.PostgreSQLDialect.querySequences (PostgreSQLDialect.java:93)
Caused by: org.postgresql.util.PSQLException: ERROR: column "sequence_name" does not exist
  Position: 8
```

This commit fixes the error for postgres 10+

See also https://github.com/rails/rails/pull/28864